# Generated by Django 3.1.2 on 2021-07-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210706_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='main',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='is_main',
        ),
        migrations.AddField(
            model_name='relationship',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='основной'),
        ),
    ]
