# Generated by Django 3.1.2 on 2021-07-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210707_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'ordering': ['-is_main', 'topic']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['topic'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(related_name='topics', through='articles.Relationship', to='articles.Article'),
        ),
    ]
